AddonId: RomM_9700aa21-447d-41b4-a989-acd38f407d9f
Packages:
  - Version: 0.2.1
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-03-24
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.1/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_1.pext
    Changelog:
      - Initial beta release of the RomM Library Importer
  - Version: 0.2.2
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-04-05
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.2/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_2.pext
    Changelog:
      - Fix crashes when null igdb_id is returned from RomM for platform
  - Version: 0.2.3
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-06-08
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.3/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_3.pext
    Changelog:
      - Update for API changes in 3.2.0 release of RomM
  - Version: 0.2.4
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-08-02
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.4/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_4.pext
    Changelog:
      - Performance, naming and code quality improvements
  - Version: 0.2.5
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-08-05
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.5/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_5.pext
    Changelog:
      - Fix fetching platforms with missing/null IGDB ID
